# Generated by Django 3.2.7 on 2021-09-03 16:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp1', '0002_login_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webapp1.login')),
                ('addressl1', models.CharField(max_length=60)),
                ('addressl2', models.CharField(max_length=60)),
                ('addcity', models.CharField(max_length=15)),
                ('addstate', models.CharField(max_length=15)),
                ('addzip', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(default='00000000', max_length=30)),
                ('patient', models.CharField(max_length=200)),
                ('doctor', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=50)),
                ('msg', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Doc_login',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=40)),
                ('email', models.CharField(default='abc@gmail.com', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medical1',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webapp1.login')),
                ('fever', models.CharField(max_length=9)),
                ('highbp', models.CharField(max_length=9)),
                ('lowbp', models.CharField(max_length=9)),
                ('seizures', models.CharField(max_length=9)),
                ('heart_d', models.CharField(max_length=9)),
                ('fainting', models.CharField(max_length=9)),
                ('diabetes', models.CharField(max_length=9)),
                ('cholestrol', models.CharField(max_length=9)),
                ('palp', models.CharField(max_length=9)),
                ('otherdetail', models.CharField(default='----', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webapp1.login')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=1)),
                ('dob', models.DateField()),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Report_sent',
            fields=[
                ('doctor', models.CharField(max_length=200)),
                ('patient', models.CharField(max_length=200)),
                ('patient_id', models.CharField(default='00000000', max_length=30)),
                ('reference_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('reference_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('albumin', models.DecimalField(decimal_places=4, max_digits=9)),
                ('rbc', models.BooleanField()),
                ('bgr', models.DecimalField(decimal_places=4, max_digits=9)),
                ('bu', models.DecimalField(decimal_places=4, max_digits=9)),
                ('createnine', models.DecimalField(decimal_places=4, max_digits=9)),
                ('sodium', models.DecimalField(decimal_places=4, max_digits=9)),
                ('patassium', models.DecimalField(decimal_places=4, max_digits=9)),
                ('haemoglobin', models.DecimalField(decimal_places=4, max_digits=9)),
                ('wbcc', models.DecimalField(decimal_places=4, max_digits=9)),
                ('rbcc', models.DecimalField(decimal_places=4, max_digits=9)),
                ('hypertension', models.BooleanField()),
                ('diabetes', models.BooleanField()),
                ('egfr', models.DecimalField(decimal_places=4, max_digits=9)),
                ('acr', models.DecimalField(decimal_places=4, max_digits=9)),
                ('pred', models.BooleanField()),
                ('stage', models.CharField(max_length=5)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='login',
            name='patient_id',
            field=models.CharField(default='00000000', max_length=30),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=40),
        ),
        migrations.CreateModel(
            name='Doc_address',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webapp1.doc_login')),
                ('addressl1', models.CharField(max_length=60)),
                ('addressl2', models.CharField(max_length=60)),
                ('addcity', models.CharField(max_length=15)),
                ('addstate', models.CharField(max_length=15)),
                ('addzip', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Doc_profile',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='webapp1.doc_login')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=1)),
                ('qualifications', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=50)),
            ],
        ),
    ]
